name: NLP_metrics
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - matplotlib=3.1.3
  - pip=20.0.2
  - python=3.8.3
  - pytorch=1.5.0
  - torchtext=0.6.0
  - pip:
    - gitpython==3.1.2
    - gpustat==1.0.0
    - jupyter==1.0.0
    - numpy==1.20.3
    - pandas==1.5.0
    - powerlaw==1.5
    - tensorboard==2.10.1
    - nltk==3.5
    - seaborn==0.11.0
    - spacy==2.3.2
    - wandb==0.13.3
    - weightwatcher==0.5.6
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz#egg=en_core_web_sm
    - https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.3.0/de_core_news_sm-2.3.0.tar.gz#egg=de_core_news_sm