METRIC_TYPES = {
    'L2': 'scale',
    'L2_DIST': 'scale',
    'PARAM_NORM': 'scale',
    'FRO_DIST': 'scale',
    'log_norm': 'scale',
    'LOG_SUM_OF_FRO': 'scale',
    'log_spectral_norm': 'scale',
    'DIST_SPEC_INIT': 'scale',
    'LOG_PROD_OF_FRO': 'scale',
    'LOG_SUM_OF_SPEC': 'scale',
    'LOG_PROD_OF_SPEC': 'scale',
    'PATH_NORM': 'scale',
    'mp_softrank': 'shape',     # missing
    'stable_rank': 'shape',
    # 'alpha': 'shape',
    'PL_alpha': 'shape',
    'TPL_alpha': 'shape',
    'exponent': 'shape',
    # 'exp_dist_exponent': 'shape',     # need to fit with exponential distribution
    'KS_distance': 'shape',
    'tail_mean_vec_entropy': 'shape',
    'bulk_mean_vec_entropy': 'shape',
    'entropy': 'shape',
    'rand_distance': 'shape',         # missing
    'alpha_weighted': 'hybrid',
    'log_alpha_norm': 'hybrid',
    'INVERSE_MARGIN': 'scale',
    'LOG_PROD_OF_SPEC_OVER_MARGIN': 'scale',
    'LOG_SUM_OF_SPEC_OVER_MARGIN': 'scale',
    'LOG_PROD_OF_FRO_OVER_MARGIN': 'scale',
    'LOG_SUM_OF_FRO_OVER_MARGIN': 'scale',
    'PATH_NORM_OVER_MARGIN': 'scale',
    'PACBAYES_INIT': 'scale',
    'PACBAYES_ORIG': 'scale',
    'PACBAYES_FLATNESS': 'scale',
    'PACBAYES_MAG_INIT': 'scale',
    'PACBAYES_MAG_ORIG': 'scale',
    'PACBAYES_MAG_FLATNESS': 'scale',

    # New metrics
    # 'W_CKA': 'scale',
    # 'FRO_OVER_SPEC': 'scale',     # same as stable_rank
    # 'LOG_SPEC_INIT_MAIN': 'scale',
    # 'LOG_SPEC_ORIG_MAIN': 'scale',
}

# The rule: look in robust first, then results
METRIC_FILES = {
    'L2': 'robust',
    'L2_DIST': 'robust',
    'PARAM_NORM': 'robust',
    'FRO_DIST': 'robust',
    'log_norm': 'results',
    'LOG_SUM_OF_FRO': 'robust',
    'log_spectral_norm': 'results',
    'DIST_SPEC_INIT': 'robust',
    'LOG_PROD_OF_FRO': 'robust',
    'LOG_SUM_OF_SPEC': 'robust',
    'LOG_PROD_OF_SPEC': 'robust',
    'PATH_NORM': 'robust',
    'mp_softrank': 'results',
    'stable_rank': 'results',
    # 'alpha': 'results',
    'PL_alpha': 'results',
    'TPL_alpha': 'results',
    'exponent': 'results',
    # 'exp_dist_exponent': 'shape',     # need to fit with exponential distribution
    'KS_distance': 'results',
    'tail_mean_vec_entropy': 'results',
    'bulk_mean_vec_entropy': 'results',
    'entropy': 'results',
    'rand_distance': 'results',
    'alpha_weighted': 'results',
    'log_alpha_norm': 'results',
    'INVERSE_MARGIN': 'robust',
    'LOG_PROD_OF_SPEC_OVER_MARGIN': 'robust',
    'LOG_SUM_OF_SPEC_OVER_MARGIN': 'robust',
    'LOG_PROD_OF_FRO_OVER_MARGIN': 'robust',
    'LOG_SUM_OF_FRO_OVER_MARGIN': 'robust',
    'PATH_NORM_OVER_MARGIN': 'robust',
    'PACBAYES_INIT': 'robust',
    'PACBAYES_ORIG': 'robust',
    'PACBAYES_FLATNESS': 'robust',
    'PACBAYES_MAG_INIT': 'robust',
    'PACBAYES_MAG_ORIG': 'robust',
    'PACBAYES_MAG_FLATNESS': 'robust',

    # New metrics
    # 'W_CKA': 'robust',
    # 'FRO_OVER_SPEC': 'robust',    # same as stable_rank
    # 'LOG_SPEC_INIT_MAIN': 'robust',
    # 'LOG_SPEC_ORIG_MAIN': 'robust',
}